use super::{ConfirmationSettings, Settings, default_plugins_dev_dir};
use crate::app::state::{PanelViewMode, SortField};

impl Default for Settings {
    fn default() -> Self {
        Self {
            show_hidden: false,
            secure_mode: false,
            default_editor: if cfg!(target_os = "windows") {
                "notepad".to_string()
            } else {
                "nano".to_string()
            },
            mouse_support: true,
            keybinding_preset: "norton".to_string(),
            theme: "slate".to_string(),
            panel_view_mode: PanelViewMode::default(),
            sort_field: SortField::default(),
            sort_reverse: false,
            show_long_names: true,
            left_panel_visible: true,
            right_panel_visible: true,
            confirmations: ConfirmationSettings::default(),

            // Tab 0
            delete_to_recycle_bin: false,
            use_system_copy_routine: false,
            copy_files_opened_for_writing: false,
            scan_symbolic_links: false,
            save_commands_history: true,
            save_folders_history: true,
            save_view_and_edit_history: true,
            use_windows_registered_types: false,
            automatic_update_env_variables: false,
            req_admin_modification: false,
            req_admin_reading: false,
            req_admin_use_additional_privileges: false,
            sorting_collation: "linguistic".to_string(),
            treat_digits_as_numbers: false,
            case_sensitive_sort: false,
            auto_save_setup: false,

            // Tab 1
            highlight_files: true,
            select_folders: true,
            right_click_selects_files: false,
            sort_folder_names_by_extension: false,
            disable_panel_update_object_count: 0,
            network_drives_autorefresh: true,
            show_column_titles: true,
            show_status_line: true,
            detect_volume_mount_points: false,
            show_files_total_information: true,
            show_free_size: false,
            show_scrollbar: false,
            show_background_screens_number: true,
            show_sort_mode_letter: true,
            show_dotdot_in_root_folders: false,
            infopanel_show_power_status: false,
            infopanel_show_cd_drive_parameters: true,
            infopanel_computer_name_format: "Physical NetBIOS".to_string(),
            infopanel_user_name_format: "Logon name".to_string(),
            file_descriptions_list_names: "Descript.ion,Files.bbs".to_string(),
            file_descriptions_set_hidden: true,
            file_descriptions_update_readonly: false,
            file_descriptions_position: 0,
            file_descriptions_update_mode: "Update if displayed".to_string(),
            file_descriptions_use_ansi: false,
            file_descriptions_save_utf8: false,
            folder_description_list_names: "DirInfo,File_Id.diz,Descript.ion,ReadMe.*,Read.Me"
                .to_string(),

            // Tab 2
            interface_clock: true,
            interface_show_key_bar: true,
            interface_always_show_menu_bar: false,
            interface_screen_saver_minutes: 5,
            interface_show_total_copy_progress: true,
            interface_show_copying_time: true,
            interface_show_total_delete_progress: false,
            interface_use_ctrl_pgup_change_drive: true,
            auto_drop_menu: false,
            interface_use_virtual_terminal: false,
            interface_fullwidth_aware_rendering: false,
            interface_cleartype_friendly_redraw: true,
            interface_console_icon: 0,
            interface_console_icon_admin_alternate: true,
            interface_window_title_addons: "%Ver %Platform %Admin".to_string(),
            dialog_history_in_edit_controls: true,
            dialog_persistent_blocks: false,
            dialog_del_removes_blocks: true,
            dialog_autocomplete: true,
            dialog_backspace_deletes_unchanged: false,
            dialog_mouse_click_outside_closes: true,
            menu_left_click_outside: "Cancel menu".to_string(),
            menu_right_click_outside: "Cancel menu".to_string(),
            menu_middle_click_outside: "Execute selected item".to_string(),
            cmdline_persistent_blocks: false,
            cmdline_del_removes_blocks: true,
            cmdline_autocomplete: true,
            cmdline_prompt_format: "$p$g".to_string(),
            cmdline_use_home_dir: "%FARHOME%".to_string(),
            autocomplete_show_list: true,
            autocomplete_modal_mode: false,
            autocomplete_append_first: false,
            enable_yazi_workflow: false,

            // Tab 4
            language: "English".to_string(),
            plugins_manager_oem_support: true,
            plugins_manager_scan_symlinks: true,
            plugins_manager_file_processing: false,
            plugins_manager_show_standard_association: false,
            plugins_manager_even_if_one_found: false,
            plugins_manager_search_results: false,
            plugins_manager_prefix_processing: false,
            plugins_developer_mode: false,
            plugins_dev_dir: default_plugins_dev_dir(),

            // Tab 5
            enter_use_external: false,
            editor_use_external: false,
            editor_expand_tabs: "Do not expand tabs".to_string(),
            editor_persistent_blocks: false,
            editor_cursor_beyond_eol: true,
            editor_del_removes_blocks: true,
            editor_select_found: false,
            editor_auto_indent: false,
            editor_cursor_at_end: false,
            editor_tab_size: 8,
            editor_show_scrollbar: false,
            editor_show_white_space: false,
            editor_show_line_numbers: false,
            editor_save_file_position: true,
            editor_save_bookmarks: true,
            editor_allow_editing_opened_writing: true,
            editor_lock_editing_readonly: false,
            editor_warn_opening_readonly: false,
            editor_autodetect_codepage: true,
            editor_default_codepage: "1252".to_string(),
            viewer_use_external: false,
            viewer_command: "".to_string(),
            viewer_persistent_selection: true,
            viewer_show_scrolling_arrows: true,
            viewer_tab_size: 8,
            viewer_visible_zero: false,
            viewer_show_scrollbar: false,
            viewer_save_file_position: true,
            viewer_save_view_mode: true,
            viewer_save_file_codepage: true,
            viewer_save_wrap_mode: false,
            viewer_save_bookmarks: true,
            viewer_detect_dump_view_mode: true,
            viewer_max_line_width: 10000,
            viewer_autodetect_codepage: true,
            viewer_default_codepage: "1252".to_string(),

            // Tab 6
            highlight_rules: crate::ui::highlight::default_highlight_rules(),
            ssh_presets: Vec::new(),

            // Git integration
            git_enabled: true,
            git_auto_detect: true,
            git_author_name: String::new(),
            git_author_email: String::new(),
            git_log_limit: 100,

            // Update
            auto_update_check: true,
            dismissed_update_version: None,

            // Plugins
            plugins: std::collections::HashMap::new(),
            plugin_settings: std::collections::HashMap::new(),
            active_dev_plugin: None,

            // Transfer Engine
            transfer_engine_enabled: true,
            transfer_default_hash: "blake3".to_string(),
            transfer_buffer_size: 1024 * 1024,
            transfer_verify_after_copy: false,
            transfer_direct_io: false,
            transfer_preserve_timestamps: true,
            transfer_preserve_attributes: true,
            transfer_max_retries: 3,
            transfer_conflict_resolution: "ask".to_string(),
            transfer_skip_symlinks: false,
            transfer_halt_on_error: false,
            transfer_preserve_acl: false,
            transfer_preserve_streams: false,
            transfer_follow_symlinks: false,
            transfer_limit_bandwidth_rate: None,
            transfer_auto_report: false,
            transfer_report_format: "html".to_string(),
        }
    }
}
