pub fn get_dependency_libraries() -> Vec<(&'static str, &'static str, &'static str)> {
    vec![
        ("ratatui", "MIT", "https://github.com/ratatui/ratatui"),
        (
            "crossterm",
            "MIT",
            "https://github.com/crossterm-rs/crossterm",
        ),
        ("tokio", "MIT", "https://github.com/tokio-rs/tokio"),
        (
            "serde",
            "MIT/Apache-2.0",
            "https://github.com/serde-rs/serde",
        ),
        (
            "serde_json",
            "MIT/Apache-2.0",
            "https://github.com/serde-rs/json",
        ),
        ("toml", "MIT/Apache-2.0", "https://github.com/toml-rs/toml"),
        (
            "directories",
            "MIT/Apache-2.0",
            "https://github.com/dirs-dev/directories-rs",
        ),
        (
            "anyhow",
            "MIT/Apache-2.0",
            "https://github.com/dtolnay/anyhow",
        ),
        (
            "thiserror",
            "MIT/Apache-2.0",
            "https://github.com/dtolnay/thiserror",
        ),
        ("log", "MIT/Apache-2.0", "https://github.com/rust-lang/log"),
        ("tracing", "MIT", "https://github.com/tokio-rs/tracing"),
        (
            "chrono",
            "MIT/Apache-2.0",
            "https://github.com/chronotope/chrono",
        ),
        ("zip", "MIT", "https://github.com/zip-rs/zip2"),
        (
            "tar",
            "MIT/Apache-2.0",
            "https://github.com/alexcrichton/tar-rs",
        ),
        (
            "flate2",
            "MIT/Apache-2.0",
            "https://github.com/rust-lang/flate2-rs",
        ),
        (
            "sevenz-rust2",
            "Apache-2.0",
            "https://github.com/hasenbanck/sevenz-rust2",
        ),
        (
            "pulldown-cmark",
            "MIT",
            "https://github.com/raphlinus/pulldown-cmark",
        ),
        (
            "image",
            "MIT/Apache-2.0",
            "https://github.com/image-rs/image",
        ),
        (
            "git2",
            "MIT/Apache-2.0",
            "https://github.com/rust-lang/git2-rs",
        ),
        (
            "futures-util",
            "MIT/Apache-2.0",
            "https://github.com/rust-lang/futures-rs",
        ),
        (
            "reqwest",
            "MIT/Apache-2.0",
            "https://github.com/seanmonstar/reqwest",
        ),
        (
            "windows-sys",
            "MIT/Apache-2.0",
            "https://github.com/microsoft/windows-rs",
        ),
        (
            "ssh2",
            "MIT/Apache-2.0",
            "https://github.com/alexcrichton/ssh2-rs",
        ),
        (
            "rustls",
            "Apache-2.0/MIT/ISC",
            "https://github.com/rustls/rustls",
        ),
        (
            "tempfile",
            "MIT/Apache-2.0",
            "https://github.com/Stebalien/tempfile",
        ),
    ]
}
