/// Returns the centralized default English translation for a key.
pub fn get_default_english_translation(key: &str) -> String {
    let val = match key {
        // Tab headers
        "tab_system" => "&System",
        "tab_panel" => "&Panel",
        "tab_interface" => "&Interface",
        "tab_confirmations" => "C&onfirmations",
        "tab_plugins" => "&Language & Plugins",
        "tab_editor" => "&Editor/Viewer",
        "tab_colors" => "&Colors",

        // Language & Plugins tab
        "lang_label" => "Main language",
        "plugins_config" => "Plugins configuration",
        "plugins_manager_settings" => "Plugins manager settings",
        "oem_support" => "OEM plugins support",
        "scan_symlinks" => "Scan symbolic links",
        "plugin_selection" => "Plugin selection",
        "file_processing" => "File processing",
        "show_std_association" => "Show standard association",
        "even_if_one" => "Even if only one plugin",
        "search_results" => "Search results (SetFindList)",
        "prefix_processing" => "Prefix processing",

        // Bottom function keys (F1-F10)
        "fkey_help" => "Help",
        "fkey_menu" => "Menu",
        "fkey_view" => "View",
        "fkey_edit" => "Edit",
        "fkey_copy" => "Copy",
        "fkey_renmov" => "RenMov",
        "fkey_mkdir" => "MkDir",
        "fkey_delete" => "Delete",
        "fkey_pulldn" => "PullDn",
        "fkey_quit" => "Quit",
        "fkey_plugin" => "Plugin",
        "fkey_screen" => "Screen",

        // F-keys with Ctrl
        "fkey_ctrl_left" => "Left",
        "fkey_ctrl_right" => "Right",
        "fkey_ctrl_name" => "Name",
        "fkey_ctrl_extens" => "Extens",
        "fkey_ctrl_time" => "Time",
        "fkey_ctrl_size" => "Size",
        "fkey_ctrl_unsort" => "Unsort",
        "fkey_ctrl_creatn" => "Creatn",
        "fkey_ctrl_access" => "Access",
        "fkey_ctrl_descr" => "Descr",
        "fkey_ctrl_owner" => "Owner",
        "fkey_ctrl_sort" => "Sort",

        // F-keys with Alt
        "fkey_alt_left" => "Left",
        "fkey_alt_right" => "Right",
        "fkey_alt_view" => "View",
        "fkey_alt_edit" => "Edit",
        "fkey_alt_print" => "Print",
        "fkey_alt_mklink" => "MkLink",
        "fkey_alt_find" => "Find",
        "fkey_alt_history" => "History",
        "fkey_alt_video" => "Video",
        "fkey_alt_tree" => "Tree",
        "fkey_viewhs" => "ViewHs",
        "fkey_foldhs" => "FoldHs",
        "fkey_ed_save" => "Save",
        "fkey_ed_hex" => "Hex",
        "fkey_ed_search" => "Search",
        "fkey_ed_discard" => "Discar",
        "fkey_ed_quit" => "Quit",
        "fkey_vw_hex" => "Hex",
        "fkey_vw_search" => "Search",
        "fkey_vw_quit" => "Quit",

        // Top menu categories
        "menu_left" => "&Left",
        "menu_files" => "&Files",
        "menu_commands" => "&Commands",
        "menu_options" => "&Options",
        "menu_right" => "&Right",

        // Left/Right menu items
        "menu_brief" => "&Brief",
        "menu_medium" => "&Medium",
        "menu_full" => "&Full",
        "menu_wide" => "&Wide",
        "menu_detailed" => "D&etailed",
        "menu_descriptions" => "&Descriptions",
        "menu_file_owners" => "File o&wners",
        "menu_file_links" => "File l&inks",
        "menu_alt_full" => "&Alt full",
        "menu_info_panel" => "I&nfo panel",
        "menu_quick_view" => "&Quick view",
        "menu_sort_modes" => "&Sort modes",
        "menu_show_long_names" => "S&how long names",
        "menu_panel_on_off" => "&Panel On/Off",
        "menu_re_read" => "&Re-read",
        "menu_change_drive" => "&Change drive",

        // Files menu items
        "menu_view" => "&View",
        "menu_edit" => "&Edit",
        "menu_copy" => "&Copy",
        "menu_rename_move" => "&Rename/Move",
        "menu_delete" => "&Delete",
        "menu_link" => "&Link",
        "menu_make_folder" => "&Make Folder",
        "menu_wipe" => "&Wipe",
        "menu_add_to_archive" => "&Add to archive",
        "menu_extract_files" => "E&xtract files",
        "menu_archive_commands" => "A&rchive commands",
        "menu_file_attributes" => "F&ile attributes",
        "menu_apply_command" => "A&pply command",
        "menu_describe_files" => "D&escribe files",
        "menu_select_group" => "&Select group",
        "menu_unselect_group" => "&Unselect group",
        "menu_invert_selection" => "&Invert selection",
        "menu_restore_selection" => "R&estore selection",

        // Commands menu items
        "menu_find_file" => "&Find file",
        "menu_history" => "&History",
        "menu_file_view_hist" => "&File view hist",
        "menu_folders_hist" => "F&olders hist",
        "menu_swap_panels" => "&Swap panels",
        "menu_panels_on_off" => "&Panels On/Off",
        "menu_compare_folders" => "&Compare folders",
        "menu_edit_user_menu" => "&Edit user menu",
        "menu_file_associations" => "File a&ssociations",
        "menu_folder_shortcuts" => "Folder s&hortcuts",
        "menu_file_panel_filter" => "File panel f&ilter",
        "menu_plugin_commands" => "&Plugin commands",
        "menu_screens_list" => "S&creens list",
        "menu_task_list" => "&Task list",
        "menu_hotplug_devices" => "H&otplug devices",

        // Options menu items
        "menu_configuration" => "&Configuration...",
        "menu_save_setup" => "&Save setup",

        // Popup titles & options
        "popup_sort_modes" => "Sort Modes",
        "popup_reverse_order" => "Reverse order",
        "popup_user_menu" => "User Commands Menu",
        "popup_select_drive" => "Select Drive ({})",
        "popup_hotlist" => "Directory Hotlist",
        "popup_actions" => "Actions",
        "popup_archive_commands" => "Archive Commands: {}",
        "no_archive_commands" => "No archive commands available.\n\n [Esc] Close",
        "archive_commands_hint" => " [Enter] Execute Option  [Esc] Close ",

        // Dialog buttons & prompts
        "btn_ok" => " OK ",
        "btn_cancel" => " Cancel ",
        "config_dialog_title" => " Configuration Settings ",
        "config_dialog_hint" => {
            " * Unimplemented/Future feature  |  [Tab/Arrows] Navigate  [Space/Enter] Edit/Toggle  [F9] Save  [Esc] Cancel"
        }

        // Prompt keys & descriptions
        "prompt_help_title" => " Help - Keybindings ",
        "key_tab" => "Tab",
        "desc_tab" => "Switch active panel",
        "key_insert" => "Insert / Space",
        "desc_insert" => "Tag/Select file for bulk ops",
        "key_f3" => "F3",
        "desc_f3" => "View highlighted file contents",
        "key_f4" => "F4",
        "desc_f4" => "Edit highlighted file",
        "key_f5" => "F5",
        "desc_f5" => "Copy tagged files to passive panel",
        "key_f6" => "F6",
        "desc_f6" => "Rename/Move files to passive panel",
        "key_f7" => "F7",
        "desc_f7" => "Make new directory",
        "key_f8" => "F8",
        "desc_f8" => "Delete tagged files",
        "key_ctrl_h" => "Ctrl+H",
        "desc_ctrl_h" => "Toggle hidden files",
        "key_ctrl_u" => "Ctrl+U",
        "desc_ctrl_u" => "Swap left and right panels",
        "key_f10" => "F10",
        "desc_f10" => "Quit application",
        "key_esc" => "Esc",
        "desc_esc" => "Close popup / Clear input",
        "col_key" => "Key",
        "col_description" => "Description",

        "prompt_copy_title" => " Copy Dialog ",
        "prompt_copy_to" => "Copy to:",
        "prompt_renmov_title" => " RenMov Dialog ",
        "prompt_renmov_to" => "Rename/Move to:",
        "prompt_mkdir_title" => " MkDir Dialog ",
        "prompt_mkdir_to" => "Make directory:",
        "prompt_delete_title" => " Delete Dialog ",
        "prompt_delete_confirm" => "Delete selected/tagged files?",
        "delete_confirm_msg" => "\n Do you really want to delete {}?\n",
        "delete_confirm_files" => "{} file(s)",
        "delete_confirm_folders" => "{} folder(s) and all their contents",
        "delete_confirm_conjunction" => " and ",
        "prompt_wipe_title" => " Wipe Dialog ",
        "prompt_wipe_confirm" => "Wipe (securely delete) selected/tagged files?",
        "prompt_error_title" => " Error Dialog ",
        "prompt_select_group_title" => " Select Group ",
        "prompt_select_group_pat" => "Select pattern (e.g. *.rs):",
        "prompt_unselect_group_title" => " Unselect Group ",
        "prompt_unselect_group_pat" => "Unselect pattern (e.g. *.rs):",
        "prompt_associations_title" => " File Associations ",
        "col_extension" => "Extension",
        "col_command" => "Command",
        "prompt_find_title" => "Find File",
        "prompt_find_folder" => "Search folder:",
        "prompt_find_pattern" => "File name pattern:",
        "prompt_find_content" => "Search content (optional):",
        "btn_cancel_braced" => "[ Esc ] Cancel",
        "prompt_shortcuts_title" => "Folder Shortcuts",
        "prompt_task_list_title" => "Task List",
        "prompt_hotplug_title" => " Hotplug Devices List ",
        "prompt_hotplug_empty" => "No hotplug devices found.",
        "prompt_attributes_title" => "File attributes",
        "prompt_add_archive_title" => "Add to archive",
        "prompt_extract_archive_title" => "Extract archive",
        "prompt_description_title" => "File description",

        // Panel Mode Names & Columns
        "panel_mode_brief" => "Brief",
        "panel_mode_medium" => "Medium",
        "panel_mode_full" => "Full",
        "panel_mode_wide" => "Wide",
        "panel_mode_detailed" => "Detailed",
        "panel_mode_desc" => "Desc",
        "panel_mode_owners" => "Owners",
        "panel_mode_links" => "Links",
        "panel_mode_alt" => "Alt",
        "col_name" => "Name",
        "col_size" => "Size",
        "col_date_modified" => "Date Modified",
        "col_ext" => "Ext",
        "col_perms" => "Perms",
        "col_owner" => "Owner",
        "col_links" => "#Links",
        "label_tagged" => "tagged",
        "label_free" => "Free:",
        "label_file" => "file",
        "label_files" => "files",
        "label_dir" => "dir",
        "label_dirs" => "dirs",

        // Viewer & Quickview
        "editor_discard_title" => " Discard Changes ",
        "editor_discard_prompt" => "Discard unsaved changes? [Y/N]",
        "viewer_title_bar" => " Viewer: [{}] {} ",
        "viewer_search_title" => " Viewer Search ",
        "viewer_search_text" => "Search for: {}",
        "view_text_mode" => "Text",
        "view_hex_mode" => "Hex",
        "view_image_mode" => "Image",
        "quickview_title" => " Quick View: {} ",
        "quickview_archive" => "Archive: {}",
        "quickview_format" => "Format: {}",
        "quickview_files" => "Files count: {}",
        "quickview_error" => "[Error reading archive: {}]",
        "quickview_binary_no_preview" => "[Binary file — cannot preview]",

        // System Settings Row Labels
        "sys_delete_recycle" => "Delete to Recycle Bin",
        "sys_system_copy" => "Use system copy routine",
        "sys_copy_opened" => "Copy files opened for writing",
        "sys_save_cmd_hist" => "Save commands history",
        "sys_save_folder_hist" => "Save folders history",
        "sys_save_view_hist" => "Save view and edit history",
        "sys_windows_types" => "Use Windows registered types",
        "sys_auto_update_env" => "Automatic update of environment variables",
        "sys_req_admin" => "Request administrator rights:",
        "sys_admin_mod" => "For modification",
        "sys_admin_read" => "For reading",
        "sys_admin_privs" => "Use additional privileges",
        "sys_sort_collation" => "Sorting collation:",
        "sys_digits_numbers" => "Treat digits as numbers",
        "sys_case_sensitive" => "Case sensitive",
        "sys_auto_save" => "Auto save setup",

        // Confirmation Settings Row Labels
        "conf_copy" => "Copy",
        "conf_move" => "Move",
        "conf_overwrite" => "Overwrite and delete R/O files",
        "conf_drag_drop" => "Drag and drop",
        "conf_delete" => "Delete",
        "conf_delete_non_empty" => "Delete non-empty folders",
        "conf_interrupt" => "Interrupt operation",
        "conf_disconnect" => "Disconnect network drive",
        "conf_delete_subst" => "Delete SUBST-disk",
        "conf_detach_vdisk" => "Detach virtual disk",
        "conf_hotplug" => "HotPlug-device removal",
        "conf_reload" => "Reload edited file",
        "conf_clear_history" => "Clear history list",
        "conf_exit" => "Exit",

        // Panel Settings Row Labels
        "pan_show_hidden" => "Show hidden and system files",
        "pan_highlight" => "Highlight files",
        "pan_select_folders" => "Select folders",
        "pan_right_click" => "Right click selects files",
        "pan_sort_folders_ext" => "Sort folder names by extension",
        "pan_reverse_sort" => "Allow reverse sort modes",
        "pan_disable_update" => "Disable automatic panel update if object count exceeds:",
        "pan_net_refresh" => "Network drives autorefresh",
        "pan_col_titles" => "Show column titles",
        "pan_status_line" => "Show status line",
        "pan_volume_points" => "Detect volume mount points",
        "pan_total_info" => "Show files total information",
        "pan_free_size" => "Show free size",
        "pan_scrollbar" => "Show scrollbar",
        "pan_bg_screens" => "Show background screens number",
        "pan_sort_letter" => "Show sort mode letter",
        "pan_dotdot_root" => "Show \"..\" in root folders",
        "pan_info_settings" => "InfoPanel settings:",
        "pan_info_power" => "Show power status",
        "pan_info_cd" => "Show CD drive parameters",
        "pan_info_computer" => "Computer name format:",
        "pan_info_user" => "User name format:",
        "pan_masks_hint" => "Groups of file masks: [Ins/Del/F4/F7/Ctrl+R]",
        "pan_modes_hint" => "Edit panel modes: [Ins/Del/F4/Ctrl+Enter]",
        "pan_desc_title" => "File descriptions:",
        "pan_desc_names" => "Names:",
        "pan_desc_hidden" => "Set \"hidden\" attribute to new lists",
        "pan_desc_readonly" => "Update read only description file",
        "pan_desc_pos" => "Position of new descriptions:",
        "pan_desc_update" => "Update mode:",
        "pan_desc_ansi" => "Use ANSI code page by default",
        "pan_desc_utf8" => "Save in UTF-8",
        "pan_folder_desc_names" => "Folder description list names:",

        // Interface Settings Row Labels
        "int_clock" => "Clock",
        "int_mouse" => "Mouse",
        "int_key_bar" => "Show key bar",
        "int_menu_bar" => "Always show the menu bar",
        "int_screensaver" => "Screen saver:",
        "int_copy_progress" => "Show total copy progress indicator",
        "int_copy_time" => "Show copying time information",
        "int_delete_progress" => "Show total delete progress indicator",
        "int_ctrl_pgup" => "Use Ctrl+PgUp to change drive",
        "int_vt" => "Use Virtual Terminal for rendering",
        "int_fullwidth" => "Fullwidth-aware rendering",
        "int_cleartype" => "ClearType-friendly redraw",
        "int_icon" => "Console icon:",
        "int_icon_admin" => "Alternate for Administrator",
        "int_title_addons" => "Far window title addons:",
        "int_diag_title" => "Dialog settings:",
        "int_diag_history" => "History in dialog edit controls",
        "int_diag_blocks" => "Persistent blocks in edit controls",
        "int_diag_del" => "Del removes blocks in edit controls",
        "int_diag_auto" => "AutoComplete in edit controls",
        "int_diag_backspace" => "Backspace deletes unchanged text",
        "int_diag_mouse" => "Mouse click outside closes dialog",
        "int_menu_title" => "Menu settings:",
        "int_menu_left" => "Left click outside:",
        "int_menu_right" => "Right click outside:",
        "int_menu_middle" => "Middle click outside:",
        "int_cmd_title" => "Command line settings:",
        "int_cmd_blocks" => "Persistent blocks",
        "int_cmd_del" => "Del removes blocks",
        "int_cmd_auto" => "AutoComplete",
        "int_cmd_prompt" => "Set prompt format:",
        "int_cmd_home" => "Use home dir:",
        "int_auto_title" => "AutoComplete settings:",
        "int_auto_list" => "Show a list",
        "int_auto_modal" => "Modal mode",
        "int_auto_append" => "Append the first matched item",
        "int_keybindings" => "Keybindings preset:",

        // Editor & Viewer Settings Row Labels
        "ed_external" => "Use external editor for F4 instead of Alt+F4",
        "ed_command" => "Editor command:",
        "ed_internal_title" => "Internal editor:",
        "ed_expand_tabs" => "Expand tabs:",
        "ed_persistent_blocks" => "Persistent blocks",
        "ed_cursor_beyond_eol" => "Cursor beyond end of line",
        "ed_del_removes_blocks" => "Del removes blocks",
        "ed_select_found" => "Select found",
        "ed_auto_indent" => "Auto indent",
        "ed_cursor_at_end" => "Cursor at the end",
        "ed_tab_size" => "Tab size:",
        "ed_show_scrollbar" => "Show scrollbar",
        "ed_show_white_space" => "Show white space",
        "ed_show_line_numbers" => "Show line numbers",
        "ed_save_pos" => "Save file position",
        "ed_save_bookmarks" => "Save bookmarks",
        "ed_allow_opened_writing" => "Allow editing files opened for writing",
        "ed_lock_readonly" => "Lock editing of read-only files",
        "ed_warn_readonly" => "Warn when opening read-only files",
        "ed_detect_codepage" => "Autodetect code page",
        "ed_default_codepage" => "Default code page:",
        "vi_external" => "Use external viewer for F3 instead of Alt+F3",
        "vi_command" => "Viewer command:",
        "vi_internal_title" => "Internal viewer:",
        "vi_persistent_selection" => "Persistent selection",
        "vi_scrolling_arrows" => "Show scrolling arrows",
        "vi_tab_size" => "Tab size:",
        "vi_visible_zero" => "Visible '\\0'",
        "vi_show_scrollbar" => "Show scrollbar",
        "vi_save_pos" => "Save file position",
        "vi_save_mode" => "Save view mode",
        "vi_save_codepage" => "Save file code page",
        "vi_save_wrap" => "Save wrap mode",
        "vi_save_bookmarks" => "Save bookmarks",
        "vi_detect_dump" => "Detect dump view mode",
        "vi_max_line" => "Maximum line width:",
        "vi_detect_codepage" => "Autodetect code page",
        "vi_default_codepage" => "Default code page:",
        "vi_codepages_hint" => "Code pages list: [Ctrl+H Ins Del F4]",

        // Colors Settings Row Labels
        "col_theme" => "Theme:",
        "col_groups" => "Color groups: [ Panel | Dialog | Menu | clock | ... ]",
        "col_highlighting" => "Files highlighting: [ +H | +S | +D | <exec> | <arc> | <temp> ]",

        // Missing column and field keys
        "col_date" => "Date",
        "col_unsorted" => "Unsorted",

        // User Commands
        "user_cmd_refresh" => "Refresh panel",
        "user_cmd_toggle_hidden" => "Toggle hidden files",
        "user_cmd_swap" => "Swap panels",
        "user_cmd_help" => "Help overlay",
        "user_cmd_close" => "Close popup",
        "user_cmd_download" => "Download/Update check",

        // Prompts and Dialogs (prompts.rs)
        "prompt_mkdir_text" => "\nEnter directory name:\n\n > {}",
        "prompt_copy_sing" => "Copying: {}",
        "prompt_copy_plur" => "Copying: {} items",
        "prompt_copy_dest" => "Destination: {}",
        "prompt_confirm_cancel_hint" => "[Enter] Confirm   [Esc] Cancel",
        "prompt_exit_title" => " Confirm Exit ",
        "prompt_exit_text" => {
            "\n Do you really want to exit Pairee?\n\n [Enter] Exit   [Esc] Cancel"
        }
        "prompt_abort_title" => " Confirm Abort ",
        "prompt_abort_text" => {
            "\n Do you want to abort the current background operation?\n\n [Enter] Abort   [Esc] Resume"
        }
        "prompt_overwrite_title" => " Confirm Overwrite ",
        "op_move" => "Move",
        "op_copy" => "Copy",
        "prompt_files_count" => "{} files",
        "prompt_overwrite_text" => {
            "\n Warning: Destination file/directory already exists!\n Destination: {}\n Target: {}\n\n Do you want to overwrite it during {}?\n\n [Enter] Overwrite   [Esc] Cancel"
        }
        "prompt_reload_title" => " Confirm Reload ",
        "prompt_reload_text" => {
            "\n Unsaved changes in the editor will be lost!\n Do you want to reload the file from disk?\n\n [Enter] Reload   [Esc] Cancel"
        }
        "prompt_clear_history_title" => " Confirm Clear History ",
        "history_type_command" => "command",
        "history_type_view" => "view",
        "history_type_folder" => "folder",
        "prompt_clear_history_text" => {
            "\n Do you want to clear the {} history list?\n\n [Enter] Clear   [Esc] Cancel"
        }
        "prompt_delete_text" => {
            "\nAre you sure you want to delete {} item(s)?\n\n[Enter] Confirm Deletion\n[Esc] Cancel"
        }
        "progress_copy_title" => " Copying Files ",
        "progress_file_label" => "File: {}",
        "progress_size_label" => "Files: {} / {}  |  Bytes: {} MB / {} MB",
        "prompt_dismiss_hint" => "[Press Enter/Esc to Dismiss]",
        "prompt_info_title" => " Information ",
        "prompt_move_sing" => "Moving: {}",
        "prompt_move_plur" => "Moving: {} items",
        "prompt_compress_title" => " Compress Archive ",
        "prompt_compress_sing" => "Compressing: {}",
        "prompt_compress_plur" => "Compressing: {} items",
        "prompt_apply_cmd_title" => " Apply Command to Selected Files ",
        "prompt_apply_cmd_sing" => "Files: {}",
        "prompt_apply_cmd_plur" => "Files ({} total): {}, ...",
        "prompt_apply_cmd_text" => {
            "\n {}\n\n Template command (use %f for file name):\n > {}\n\n [Enter] Execute   [Esc] Cancel"
        }
        "prompt_describe_text" => {
            "\n File: {}\n Current Description: {}\n\n New Description:\n > {}\n\n [Enter] Save   [Esc] Cancel"
        }
        "prompt_symlink_title" => " Create Symbolic Link ",
        "prompt_hardlink_title" => " Create Hard Link ",
        "prompt_link_text" => {
            "\n Source: {}\n Link Path Destination:\n\n > {}\n\n [Enter] Confirm   [Esc] Cancel"
        }
        "prompt_filter_title" => " File Mask Filter ",
        "prompt_filter_text" => {
            "\n Enter mask filter (e.g. *.rs; empty to show all):\n\n > {}\n\n [Enter] Apply   [Esc] Cancel"
        }
        "prompt_wipe_warn_title" => " WARNING: Secure Wipe Confirm ",
        "prompt_wipe_warn_text" => {
            "\n Are you sure you want to SECURELY WIPE {} item(s)?\n This writes over files and is IRRECOVERABLE.\n\n [Enter] Wipe   [Esc] Cancel"
        }
        "prompt_save_setup_title" => " Save Setup ",
        "prompt_save_setup_text" => {
            "\n Save configuration and current layout settings?\n\n [Enter] Confirm   [Esc] Cancel"
        }

        // File Info (info.rs)
        "info_panel_title" => " File Information ",
        "info_attrs_title" => " File Attributes ",
        "info_yes" => "Yes",
        "info_no" => "No",
        "info_na" => "N/A",
        "info_attrs_text" => {
            "\n Name: {}\n Path: {}\n Size: {} bytes\n Owner: {}\n Links: {}\n Readonly: {}\n Modified: {}\n Created: {}\n\n Unix Permissions (octal):\n > {}\n\n [Enter] Save   [Esc] Cancel"
        }

        // History Lists (history_lists.rs)
        "history_command_title" => " Command History ",
        "history_command_empty" => "\n No command history.\n\n [Esc] Close",
        "history_command_hint" => " [Enter] Execute command  [Esc] Close ",
        "history_view_title" => " File View History ",
        "history_view_empty" => "\n No viewed file history.\n\n [Esc] Close",
        "history_view_hint" => " [Enter] View / Edit File  [Esc] Close ",
        "history_folder_title" => " Folder Navigation History ",
        "history_folder_empty" => "\n No folder history.\n\n [Esc] Close",
        "history_folder_hint" => " [Enter] Jump to Folder  [Esc] Close ",
        "prompt_search_title" => " Search Files ",
        "prompt_search_text" => {
            "\n Search in: {}\n{}File name query: {}\n{}Content query: {}\n\n [Tab] Switch Field   [Enter] Search   [Esc] Cancel"
        }
        "search_results_title" => " Search Results: \"{}\" ({} found) ",
        "searching_suffix" => " (searching...)",
        "searching_placeholder" => "\n Searching, please wait...\n\n [Esc] Cancel",
        "search_results_empty" => "\n No files found.\n\n [Esc] Close",
        "search_results_hint" => " [Enter] Navigate to  [Esc] Close ",
        "tree_view_title" => " Directory Tree ",
        "tree_view_hint" => " [Enter] Navigate  [Esc] Close ",
        "compare_results_title" => " Folder Compare Results ",
        "compare_results_empty" => "\n All files are identical.\n\n [Esc] Close",
        "compare_status_only_left" => "Only in Left",
        "compare_status_only_right" => "Only in Right",
        "compare_status_different" => "Different Size/Time",
        "compare_status_equal" => "Equal",
        "compare_results_hint" => {
            " [Esc] Close  (Differences are automatically tagged in active panel) "
        }
        "task_list_title" => " Task List (OS Processes) ",
        "task_list_empty" => "\n No processes listed.\n\n [Esc] Close",
        "col_pid" => "PID",
        "col_process_name" => "Process Name",
        "col_memory" => "Memory (MB)",
        "task_list_hint" => " [Del / Alt+Del] Kill process  [Esc] Close ",
        "associations_empty" => "\n No rules configured.\n\n [Esc] Close",
        "col_mask" => "Mask",
        "col_open_command" => "Open Command",
        "col_view_command" => "View Command (F3)",
        "associations_same_as_open" => "(Same as open)",
        "hint_esc_close" => " [Esc] Close ",

        // Editor (editor.rs)
        "editor_title" => " Editor - {} {} ",
        "editor_status_text" => " Line Chars: {} | Total Lines: {} | Pos: ({}, {})",
        "editor_search_title" => " Search Text ",
        "editor_search_text" => "\n Search query:\n > {}\n\n [Enter] Search   [Esc] Cancel",

        "prompt_process_multiple" => "Process multiple destinations",
        "prompt_process_multiple_names" => "Process multiple names",
        "prompt_copy_files_access" => "Copy files access mode",
        "prompt_copy_ext_attr" => "Copy extended attributes",
        "prompt_disable_write_cache" => "Disable write cache",
        "prompt_produce_sparse_files" => "Produce sparse files",
        "prompt_use_cow" => "Use copy-on-write if possible",
        "prompt_symlinks" => "With symlinks:",
        "prompt_use_filter" => "Use filter",
        "btn_ok_bracket" => "{ OK }",
        "btn_cancel_bracket" => "[ Cancel ]",
        "btn_copy_bracket" => "{ Copy }",
        "btn_rename_bracket" => "{ Rename }",
        "btn_delete_bracket" => "{ Delete }",
        "btn_f10_tree" => "[ F10-Tree ]",
        "btn_filter" => "[ Filter ]",
        "opt_smartly_copy" => "Smartly copy",
        "opt_copy_link" => "Copy link",
        "opt_copy_target" => "Copy target",
        "prompt_already_existing" => "Already existing files:",
        "opt_ask" => "Ask",
        "opt_overwrite" => "Overwrite",
        "opt_skip" => "Skip",
        "opt_append" => "Append",
        "progress_initializing" => "Initializing...",
        "error_move_failed" => "Move failed:",
        "error_delete_failed" => "Delete failed:",
        "progress_wiping" => "Wiping...",

        _ => key,
    };
    val.to_string()
}
